### ISSUE TITLE
watch for 2.8.1 release

### ISSUE THREAD

**Issue by sjrand** [palantir/hadoop#20]
https://issues.apache.org/jira/browse/HDFS-9276 will be part of the 2.8.1 release, at which point the only concrete reason to have this repo is the backport of KMS support in s3a which is targeting 2.9.0

**Comment by ash211** [comment]
What about the rest of the stuff in the changelog? https://github.com/palantir/hadoop/blob/branch-2.8.0/PALANTIR-CHANGELOG.md#280-palantir3

Revert HADOOP-13188 sounds like the harder one to me

**Comment by sjrand** [comment]
HADOOP-12705, HADOOP-13050, and HADOOP-13075 are all part of supporting KMS, as is using the fix of HADOOP-14028 from branch-2 instead of the one in branch-2.8.0.

The revert of HADOOP-13188 is just a workaround for a limitation in one of our internal apps, and we could fix that application if we needed to. In fact there's already a PR that fixes it -- just need to convince people to merge it.

**Comment by sjrand** [comment]
silly thing to make a ticket for -- obviously I'm doing this anyway, and watching for a release isn't particular actionable
