### ISSUE TITLE
rebase off of 2.8.1

### ISSUE THREAD

**Issue by sjrand** [palantir/hadoop#22]
Apache Hadoop 2.8.1 was stealthily tagged on May 20th to fix https://issues.apache.org/jira/browse/YARN-6709. We don't use this feature, but still seems like a good idea to pick up the fix in case someone decides to try it out.

**Comment by ash211** [comment]
Need this to keep clients on the Palantir release -- otherwise `2.8.1` > `2.8.0-palantir6` so automatic version bumpers pull clients off of Palantir Hadoop and back to Apache Hadoop

**Comment by sjrand** [comment]
2.8.0-palantir.7 contains the security fixes that went into 2.8.1, so this should be good now

the automatic version bumper thing can be handled separately I think
