### ISSUE TITLE
speed up tests

### ISSUE THREAD

**Issue by sjrand** [palantir/hadoop#3]
Even a 4-hour timeout wasn't enough, and https://circleci.com/gh/palantir/hadoop/120 has been running for almost seven hours now.

Some ideas to experiment with:

* Test the different modules in parallel. Have n circle containers, each of which starts by compiling all the code but not running any tests, and then runs the tests for only a couple of modules.
* Skip tests for modules we don't care about, e.g., Azure support, BookKeeper implementation of shared edit logs.

cc @ash211 @robert3005 in case you guys have more ideas

**Comment by ash211** [comment]
Looks like 8 hours isn't even enough...  Try 16?

Agreed we're going to have to speed these tests up.  Skipping modules of certain tests and running tests in parallel across N containers both sound like good ideas.

**Comment by sjrand** [comment]
This is in a much better place now after a couple of changes:

* Run tests in parallel across 5 different containers, one for each project that needs to be tested:

   * hadoop-common
   * hadoop-hdfs
   * hadoop-mapreduce
   * hadoop-yarn
   * hadoop-tools

* Don't run the tests for `hadoop-client`. There aren't actually any tests (or code) in that project, it just redundantly runs the tests for the above projects and takes forever.

Not quite ready to call this closed because the container that runs the hadoop-yarn tests takes 6 hours to complete -- feels like we should be able to do better.

**Comment by sjrand** [comment]
Doing better now after using maven less incompetently -- builds take about 4 hours total, including both tests and publishing JARs and the dist.

* hadoop-common finishes in about 35 minutes
* **hadoop-hdfs** is the bottleneck, finishing in 3 hours and 40 minutes

   * dominated by Apache Hadoop HDFS, which is almost the entirety of the test runtime

* hadoop-mapreduce finishes in 2.5 hours

   * dominated by Apache Hadoop MapReduce JobClient, which is over 2 hours

* hadoop-tools finishes in only 14 minutes
* hadoop-yarn finishes in about 2 hours

   * dominated by Apache Hadoop YARN ResourceManager, which is 1 hour and 20 minutes

Four hours seems acceptable, and since there's no real benefit to splitting the `hadoop-hdfs/hadoop-hdfs` module into its own container, I don't see how to do better, so closing.
