### ISSUE TITLE
Can we publish sources?

### ISSUE THREAD

**Issue by j-baker** [palantir/hadoop#31]
Internally we depend on jars from this fork of hadoop. It's annoying that we have no source code included with this!

**Comment by sjrand** [comment]
PRs welcome :)

(I'll try to look at this today, but no guarantee of not getting sidetracked)

**Comment by ash211** [comment]
+1

**Comment by sjrand** [comment]
Looks like the PR worked -- https://bintray.com/palantir/releases/hadoop/2.9.0-palantir.5#files/org%2Fapache%2Fhadoop%2Fhadoop-aws%2F2.9.0-palantir.5
