### ISSUE TITLE
Revert our backport of HADOOP 14475

### ISSUE THREAD

**Issue by ashrayjain** [palantir/hadoop#40]
Look at https://issues.apache.org/jira/browse/HADOOP-15392 for more context but it looks like 14475 introduced some pretty serious memory leaks.

CC @ellisjoe @sjrand

**Comment by ashrayjain** [comment]
This has been causing OOMs for us pretty consistently since switching to 2.9.0-palantir.5 and looking at heap dumps points to the same root cause (metrics things) as that ticket.

**Comment by sjrand** [comment]
@ashrayjain, can you comment on https://issues.apache.org/jira/browse/HADOOP-15392 with any info you have? (The fact that you're also seeing this alone is helpful btw).

**Comment by sjrand** [comment]
Also, 2.9.1-palantir.1 won't have HADOOP-14475 backported -- will close this once that's released.

**Comment by sjrand** [comment]
Fixed in https://github.com/palantir/hadoop/releases/tag/2.9.1-palantir.1.
